export const projects = [
  {
    title: "AstroJet",
    date: "October 2023",
    description: "MERN-stack application for booking flights to other planets!",
    tech: ["React", "Node.js", "Express.js", "MongoDB", "Heroku"],
    img: "https://raw.githubusercontent.com/gorgeousPotato/screenshots_spendwise/main/Screenshot%202024-01-10%20at%2010.11.23%20PM.png",
    github: "https://github.com/gorgeousPotato/astrojetairways",
    deployed: "https://astrojet-b7b83b6f90f3.herokuapp.com/",
  },
  {
    title: "Allergy Alchemy",
    date: "October 2023",
    description: "MERN-stack application for people with food allergies – to keep track of their allergens, search for recipes that don’t contain allergens, create new recipes to share with the world, keep track of daily nutrition (via Edamam Nutrition API), create shopping lists.",
    tech: ["React", "Node.js", "Express.js", "MongoDB", "JSON API", "AWS", "Heroku"],
    img: "https://github.com/gorgeousPotato/mern-allergy-alchemy/blob/main/screenshots/6.png?raw=true",
    github: "https://github.com/gorgeousPotato/mern-allergy-alchemy",
    deployed: "https://allergy-alchemy-09e7006da636.herokuapp.com/",
  },
  {
    title: "SpendWise",
    date: "September 2023",
    description: "Team project - a user-friendly and efficient expense tracker application designed to help you effortlessly manage your finances. With its intuitive interface, SpendWise allows you to easily record and categorize your expenses, set budgets, and gain valuable insights into your spending habits. Take control of your financial journey with SpendWise and make informed decisions to achieve your financial goals.",
    tech: ["Python", "Django", "PostgreSQL", "Chart.js", "Heroku"],
    img: "https://github.com/gorgeousPotato/screenshots_spendwise/raw/main/1.png",
    github: "https://github.com/gorgeousPotato/ExpenseTrackerH4B",
    deployed: "https://spendwise-jln-aca0c142cd27.herokuapp.com/",
  },
  {
    title: "Merry-Go-Round",
    date: "August 2023",
    description: "full-stack application designed for parents to easily locate nearby playgrounds. In the past, we used to rely on Google to find parks and then attempt to determine the presence and size of playgrounds through reviews and images. However, with Merry-Go-Round, everything is consolidated in a single platform. Within the Merry-Go-Round application, you can access a comprehensive database of playgrounds worldwide, visualize their locations on a map, and even calculate the distance to each of them!",
    tech: ["Node.js", "Express.js", "MongoDB", "Mapbox API", "Heroku"],
    img: "https://github.com/gorgeousPotato/merry-go-round/raw/main/public/images/screenshots/8.png",
    github: "https://github.com/gorgeousPotato/ExpenseTrackerH4B",
    deployed: "https://merrygoround-35cce2c39443.herokuapp.com/playgrounds",
  },
  {
    title: "Battleship",
    date: "August 2023",
    description: "Battleship is a strategic guessing game designed for two players. I implemented AI algorythms for computer's choices.  Players strategically position their ships on their respective boards, keeping the ship locations concealed from their opponent. Players take turns making 'shots' in an attempt to target and sink each other's ships. ",
    tech: ["HTML", "CSS", "JavaScript", "Drag and Drop API", "AI"],
    img: "https://github.com/gorgeousPotato/battleship/raw/main/images/screenshots/4.the%20beginning%20of%20the%20game.png",
    github: "https://github.com/gorgeousPotato/battleship",
    deployed: "https://gorgeouspotato.github.io/battleship/",
  },
]